blog/urls.py
from django.urls import path
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from django.views.decorators.cache import never_cache

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('view/<slug>/', BlogDetailView.as_view(), name='view'),
    path('update/<slug>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<slug>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.views import (contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView,
                           ProductDeleteView, CategoryListView)

app_name = 'catalog'
urlpatterns = [
    path('', CategoryListView.as_view(), name='main_index'),
    path('product/<int:pk>', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', cache_page(30)(ProductDetailView.as_view()), name='product'),
    path('product/create/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('contacts/', contacts, name='contacts'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import (UserRegisterView, ProfileView, verify_mail, UserForgotPasswordView, GenerateNewPassword,
                         generate_new_password)
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('reset_password/', UserForgotPasswordView.as_view(), name='reset_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', UserRegisterView.as_view(), name='reg'),
    path('verification_code/<str:code>/', verify_mail, name='verification_code'),
    path('profile/edit/', ProfileView.as_view(), name='profile'),
    path('set_new_password/<uidb64>/<token>/', GenerateNewPassword.as_view(), name='set_new_password'),
    path('profile/new_pass', generate_new_password, name='new_pass')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from catalog.models import NULLABLE


# Create your models here.
class User(AbstractUser):
    username = None  # для деактивации главного поля авторизации
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='Страна', **NULLABLE)
    email = models.EmailField(unique=True, verbose_name='Почта')
    is_active = models.BooleanField(default=False)
    verification_code = models.CharField(max_length=4, verbose_name='Код верификации', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from catalog.forms import StyleFormMixin
from users.models import User
from django import forms


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, View
from users.models import User
from users.forms import UserRegisterForm, UserProfileForm
from django.urls import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.mail import send_mail
from config.settings import EMAIL_HOST_USER
from catalog.forms import StyleFormMixin
import random
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView


# Create your views here.
class UserRegisterView(CreateView):
    """
    Контроллер регистрации пользователя
    """
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/reg.html'

    def form_valid(self, form):
        """
        Верификация почты по ссылке
        """
        new_user = form.save()
        code = ''.join(random.sample('0123456789', 4))
        new_user.verification_code = code
        send_mail(
            subject='Верификация SkyStore',
            message=f'''Перейдите по ссылке для верификации: http://127.0.0.1:8000/users/verification_code/{code}
и введите Логин и пароль''',
            from_email=EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


def verify_mail(request, code):
    """
    Контроллер верификации email
    """
    user = User.objects.get(verification_code=code)
    user.is_active = True
    user.save()
    messages.success(request, 'Ваш аккаунт активирован!')
    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    """
    Контроллер редактирования профиля пользователя
    """
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserProfileForm

    def get_object(self, queryset=None):
        """
        Чтобы не передавать pk
        """
        return self.request.user


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """
    form_class = PasswordResetForm
    from_email = EMAIL_HOST_USER
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Письмо с новым паролем отправлено на ваш email'
    # subject_template_name = 'Восстановление пароля на сайте SkyStore'
    email_template_name = 'users/mail_password_reset.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на восстановление пароля'
        return context


def generate_new_password(request):
    """
    Контроллер генерации нового пароля и отправка его на почту
    """
    new_password = User.objects.make_random_password()
    request.user.set_password(new_password)
    request.user.save()
    send_mail(
        subject='Изменение пароля',
        message=f'Ваш новый пароль для авторизации: {new_password}',
        from_email=EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    messages.success(request, 'Вам на почту отправлено письмо с новым паролем для вашего аккаунта')
    return redirect(reverse('users:login'))


class GenerateNewPassword(SuccessMessageMixin, View):
    """
    Контроллер восстановления генерации пароля, если пользователь забыл свой пароль
    """
    def get(self, request, uidb64: str, token: str):
        user = self.get_user(uidb64)
        from django.contrib.auth.tokens import default_token_generator
        if not user or not default_token_generator.check_token(user, token):
            messages.warning(self.request, 'Ошибка подтверждения, попробуйте ещё раз.')
        else:
            new_password = User.objects.make_random_password()
            user.set_password(new_password)
            user.save()
            send_mail(
                subject='Восстановление пароля',
                message=f'Ваш новый пароль для авторизации: {new_password}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email]
            )
            messages.success(request, 'Вам на почту отправлено письмо с новым паролем для вашего аккаунта')
            return redirect(reverse('users:login'))

    @staticmethod
    def get_user(uid_base64: str) -> User | None:
        try:
            from django.utils.http import urlsafe_base64_decode
            uid = urlsafe_base64_decode(uid_base64).decode()
            user_id = int(uid)
            user = User.objects.get(pk=user_id)
        except (ValueError, User.DoesNotExist):
            user = None
        return user

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container">
    {% if messages %}
        <div class="alert alert-warning">
            {% for message in messages %}
                {{ message }}<br/>
            {% endfor %}
        </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Авторизация</div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Войти
                        </button>
                        <a class="btn btn-outline-warning" href="{% url 'catalog:main_index' %}">Отмена</a>
                        <a href="{% url 'users:reset_password' %}">Пароль забыт</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/mail_password_reset.html
{% autoescape off %}
    
    Вы получили это электронное письмо, потому что запросили сброс пароля для своей учетной записи пользователя на {{ site_name }}.

	Перейдите на следующую страницу и получите новый пароль:
	{% block reset_link %}
	    {{ protocol }}://{{ domain }}{% url 'users:set_new_password' uidb64=uid token=token %}
	{% endblock %}
	Ваше имя пользователя: {{ user.email }}

{% endautoescape %}

users/templates/users/reg.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Регистрация</div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <h6>Для подтверждения регистрации проверте почту!</h6>
                        <button type="submit" class="btn btn-success">
                            Зарегистрироваться
                        </button>
                        <a class="btn btn-outline-warning" href="{% url 'catalog:main_index' %}">Отмена</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Редактирование профиля</div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Сохранить
                        </button>
                        <a class="btn btn-outline-warning" href="{% url 'catalog:main_index' %}">Отмена</a>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'users:new_pass' %}" class="btn btn-danger">Сгенерировать новый пароль</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
    {% endblock %}

users/templates/users/user_password_reset.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Ведите email, который указывали при регистрации</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Восстановить пароль</button>
            </form>
        </div>
    </div>

{% endblock %}