blog/urls.py
from django.urls import path
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from django.views.decorators.cache import never_cache

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('view/<slug>/', BlogDetailView.as_view(), name='view'),
    path('update/<slug>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<slug>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache
from catalog.views import (contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView,
                           ProductDeleteView, CategoryListView)

app_name = 'catalog'
urlpatterns = [
    path('', CategoryListView.as_view(), name='main_index'),
    path('product/<int:pk>', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', cache_page(30)(ProductDetailView.as_view()), name='product'),
    path('product/create/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='delete_product'),
    path('contacts/', contacts, name='contacts'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.conf import settings
from django.db import models

# Create your models here.
NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=500, verbose_name='Описание')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('title',)


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=500, verbose_name='Описание')
    image = models.ImageField(upload_to='images/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.FloatField(verbose_name='Цена за покупку')
    date_of_create = models.DateField(verbose_name='Дата создания')
    date_of_change = models.DateField(verbose_name='Дата последнего изменения', auto_now_add=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='Владелец продукта')
    is_published = models.BooleanField(default=False, verbose_name='Продается')

    def __str__(self):
        return f'''{self.title}:
{self.description}'''

    class Meta:
        verbose_name = 'Приложение'
        verbose_name_plural = 'Приложения'
        ordering = ('category',)
        permissions = [
            (
                'set_is_published',
                'Can public for sale'
            ),
            (
                'set_description',
                'Can edit description'
            ),
            (
                'set_category',
                'Can change category'
            )
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.CharField(max_length=50, verbose_name='Номер версии')
    title = models.CharField(max_length=150, verbose_name='Название версии', **NULLABLE)
    is_current = models.BooleanField(default=False, verbose_name='Активная')

    def __str__(self):
        return f'''{self.product}, 
версия: {self.version_number} {self.title}'''

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('product', 'title',)

# @receiver(post_save, sender=Version)
# def set_active_version(sender, instance, **kwargs):
#     if instance.is_active:
#         Version.objects.filter(product=instance.product).exclude(pk=instance.pk).update(is_active=False)

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_current' and field_name != 'is_published':
                field.widget.attrs['class'] = 'form-control'
            # field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    danger_words = ('казино', 'криптовалюта', 'крипта', 'биржа',
                    'дешево', 'бесплатно', 'обман', 'полиция', 'радар',)

    class Meta:
        model = Product
       # exclude = ('owner',)
        fields = '__all__'

    def clean_title(self):
        cleaned_data = self.cleaned_data['title']
        for word in self.danger_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('>|< ПОЛИЦИЯ УЖЕ ВЫЕХАЛА ЗА ТОБОЙ >|<')
        else:
            return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for word in self.danger_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('>|< ПОЛИЦИЯ УЖЕ ВЫЕХАЛА ЗА ТОБОЙ >|<')
        else:
            return cleaned_data


class ModeratorProductForm(ProductForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.models import Product, Version, Category
from catalog.forms import ProductForm, VersionForm, ModeratorProductForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.conf import settings
from django.core.cache import cache
from catalog.services import get_cache_category


# Create your views here.
class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'catalog/main_list.html'
    extra_context = {
        'title': 'SkyStore - Магазин и Блог, Блогазин, Магалог'
    }

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_cache_category()
        return context_data


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/product_list.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context['category_pk'] = category_item.pk
        context['title'] = f'''Все проги категории: {category_item.title}'''
        for product in context['object_list']:
            active_version = product.version_set.filter(is_current=True).first()
            if active_version:
                product.active_version_number = active_version.version_number
                product.active_title = active_version.title
            else:
                product.active_version_number = ''
                product.active_title = 'Доступна тестовая версия'

        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'), )
        if (not self.request.user.is_staff and not self.request.user.is_superuser
                and not self.request.user.groups.filter(name='moderators')):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product.html'
    extra_context = {
        'title': 'SkyStore'
    }


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    login_url = "users:login"
    permission_required = 'catalog.add_product'

    # success_url = reverse_lazy('catalog:index')
    def get_success_url(self):
        return reverse_lazy('catalog:product', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    login_url = "users:login"

    # permission_required = ('catalog.change_product', 'set_is_published', 'set_description', 'set_category',)

    # success_url = reverse_lazy('catalog:index')
    def get_success_url(self):
        return reverse_lazy('catalog:product', args=[self.object.pk])

    # def get_object(self, queryset=None):
    #     self.object = super().get_object(queryset)
    #     if (self.request.user != self.object.owner and not self.request.user.is_staff
    #             and not self.request.user.is_superuser and self.request.user.has_perm('catalog.set_published')):
    #         raise Http404
    #     else:
    #         return self.object

    def get_form_class(self):
        """Return the form class to use."""
        if not self.request.user.is_staff or self.request.user.is_superuser or not self.request.user.groups.filter(
                name='moderators'):
            self.form_class = ProductForm
        else:
            self.form_class = ModeratorProductForm
        return self.form_class

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def test_func(self):
        _user = self.request.user
        _instance: Product = self.get_object()
        custom_perms: tuple = (
            'catalog.set_is_published',
            'catalog.set_category',
            'catalog.set_description',
        )
        print(_user.groups.all())
        print(_user.is_superuser)
        if _user == _instance.owner:
            print('owner')
            return True
        elif _user.is_superuser:
            print('superuser')
            return True
        elif _user.groups.filter(name='moderators') and _user.has_perms(custom_perms):
            print('moderator')
            return True
        else:
            print('no permissions')
            return self.handle_no_permission()


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    # success_url = reverse_lazy('catalog:product_list')
    login_url = "users:login"
    permission_required = 'catalog.delete_product'

    def get_success_url(self):
        return reverse_lazy('catalog:product_list', args=[self.object.category.pk])

    def get_context_data(self, **kwargs):
        """Переопределение метода """
        context_data = super().get_context_data(**kwargs)
        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['product_pk'] = product_item.pk
        context_data['title'] = f'Удаление программы {product_item.title}'
        return context_data


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"""
Имя: {name},
Телефон: {phone},
Сообщение:'{message}'""")
    return render(request, 'catalog/contacts.html')

# def product(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     products = Product.objects.filter(id=pk)
#     context = {
#         'product_list': products,
#         'title': f'Описание проги {product_item.title}'
#     }
#     return render(request, 'catalog/product.html', context)

catalog/templates/catalog/base.html
{% load static %}
{% load my_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/includes/menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">{% now 'd-M' %}</p>
</div>

{% block content %}

{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contact.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message"
                                      placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <input class="btn btn-primary" type="submit" value="Отправить">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message"
                                      placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <input class="btn btn-primary" type="submit" value="Отправить">
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="col-12 mb-5">
        {% if perms.dogs_app.add_dogs %}
        <a class="btn btn-outline-primary mb-5" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
        {% endif %}
        <div class="row text-center">
            {% for object in product_list %}
            <div class="col-3">
                <h5 class="my-0 font-weight-normal">{{ object.category }}:</h5>
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h5 class="my-0 font-weight-normal">{{ object.title }}:</h5>
                        <h5 class="my-0 font-weight-normal">{{ object.description }}</h5>
                        <hr>
                        <h5 class="my-0 font-weight-normal">by: {{ object.owner|default:"SkyStore" }}</h5>
                    </div>
                    <div class="card-body">
                        <h6>Версия: {{ object.active_version_number }} {{ object.active_title }}</h6>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- Подписка на 1 год</li>
                            <li>- Поддержка</li>
                            <li>- Получение обновлений</li>
                        </ul>
                        <h2 class="card-title pricing-card-title">Цена: {{ object.price }}</h2>
                        <a class="btn btn-primary" href="{% url 'catalog:product' object.pk %}" role="button">Подробнее</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/main_list.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary mb-5" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
        <div class="row text-center">
            {% for object in object_list %}
            <div class="col-3">
                <h5 class="my-0 font-weight-normal">:-)  (-:</h5>
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h5 class="my-0 font-weight-normal">{{ object.title }}:</h5>
                        <hr>
                        <h5 class="my-0 font-weight-normal">{{ object.description }}</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- Подписка на 1 год</li>
                            <li>- Поддержка</li>
                            <li>- Получение обновлений</li>
                        </ul>
                        <a class="btn btn-primary" href="{% url 'catalog:product_list' object.pk %}" role="button">К продуктам</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-0">
            <h5 class="my-0 font-weight-normal">{{ object.category }}:</h5>
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal">{{ object.title }}:</h5>
                    <h5 class="my-0 font-weight-normal">{{ object.description }}</h5>
                    <h5 class="my-0 font-weight-normal">by: {{ object.owner|default:"SkyStore" }}</h5>
                </div>
                <div class="card-body">
                    <img src="{{ object.image|image_files }}"/>
                    <h2 class="card-title pricing-card-title">Цена: {{ object.price }}</h2>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Подписка на 1 год</li>
                        <li>- Поддержка</li>
                        <li>- Получение обновлений</li>
                    </ul>
                </div>
                <div class="card-footer">
                    <a class="btn btn-link" href="{% url 'catalog:update_product' object.pk %}">Редактировать</a>
                    {% if perms.catalog.delete_product %}
                        <a class="btn btn-outline-danger float-right" href="{% url 'catalog:delete_product' object.pk %}">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="col-12 mb-5">
        <form method="post" class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Удаление проги
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        <p>Действительно хотите удались этот продукт-прогу {{ object.title }}?</p>
                        <button type="submit" class="btn btn-outline-danger">
                            Удалить
                        </button>
                        <a class="btn btn-outline-warning" href="{% url 'catalog:product' object.pk %}">Отмена</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Добавление приложения</div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить изменения
                            {% else %}
                                Добавить прогу
                            {% endif %}
                        </button>
                        <a class="btn btn-outline-warning" href="{% url 'catalog:main_index' %}">Отмена</a>
                    </div>
                </div>
            </div>
            {% if user == object.owner or user.is_superuser %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Добавление версии приложения</div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_table }}
                            {% if not forloop.last %}
                                <hr>
                                <hr>
                            {%endif%}
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="col-12 mb-5">
        {% if perms.catalog.add_product %}
        <a class="btn btn-outline-primary mb-5" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
        {% endif %}
        <div class="row text-center">
            {% for object in product_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h5 class="my-0 font-weight-normal">{{ object.title }}:</h5>
                        <h5 class="my-0 font-weight-normal">{{ object.description }}</h5>
                        <hr>
                        <h5 class="my-0 font-weight-normal">by: {{ object.owner|default:"SkyStore" }}</h5>
                    </div>
                    <div class="card-body">
                        <h6>Версия: {{ object.active_version_number }} {{ object.active_title }}</h6>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- Подписка на 1 год</li>
                            <li>- Поддержка</li>
                            <li>- Получение обновлений</li>
                        </ul>
                        <h2 class="card-title pricing-card-title">Цена: {{ object.price }}</h2>
                        <a class="btn btn-primary" href="{% url 'catalog:product' object.pk %}" role="button">Подробнее</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}